// Prepares project images for the site.
//
// Usage: drop new PNG screenshots into src/assets/product_showcase/<project>/ and run
//   npm run optimize:images
//
// 1. Each PNG is resized to at most MAX_WIDTH, written next to itself as .webp, and the
//    original is moved to assets-originals/ (git-ignored) so it never ships in the bundle.
// 2. The pixel size of every showcase screenshot and certificate is written to
//    src/data/image-sizes.generated.ts. The site uses it to reserve the right amount of space
//    before an image loads, so the page does not jump and a skeleton can be shown.
import { mkdir, readdir, rename, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const MAX_WIDTH = 1600;
const QUALITY = 80;

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const assetsDir = path.join(root, "src", "assets");
const showcaseDir = path.join(assetsDir, "product_showcase");
const certificationsDir = path.join(assetsDir, "certifications");
const originalsDir = path.join(root, "assets-originals", "product_showcase");
const manifestFile = path.join(root, "src", "data", "image-sizes.generated.ts");

const formatMb = (bytes) => `${(bytes / 1024 / 1024).toFixed(1)} MB`;

async function optimizeScreenshots() {
  let before = 0;
  let after = 0;
  let count = 0;

  for (const project of await readdir(showcaseDir, { withFileTypes: true })) {
    if (!project.isDirectory()) continue;

    const projectDir = path.join(showcaseDir, project.name);
    for (const file of await readdir(projectDir)) {
      if (!/\.png$/i.test(file)) continue;

      const source = path.join(projectDir, file);
      const target = path.join(projectDir, file.replace(/(\.png)+$/i, ".webp"));

      await sharp(source)
        .resize({ width: MAX_WIDTH, withoutEnlargement: true })
        .webp({ quality: QUALITY })
        .toFile(target);

      before += (await stat(source)).size;
      after += (await stat(target)).size;
      count += 1;

      const archiveDir = path.join(originalsDir, project.name);
      await mkdir(archiveDir, { recursive: true });
      await rename(source, path.join(archiveDir, file));
    }
  }

  console.log(
    count
      ? `Optimized ${count} images: ${formatMb(before)} -> ${formatMb(after)}`
      : "No new PNG screenshots to optimize.",
  );
}

async function listImages(dir, extensions) {
  const found = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) found.push(...(await listImages(full, extensions)));
    else if (extensions.test(entry.name)) found.push(full);
  }
  return found;
}

async function writeSizeManifest() {
  const files = [
    ...(await listImages(showcaseDir, /\.webp$/i)),
    ...(await listImages(certificationsDir, /\.(png|jpe?g|webp)$/i)),
  ];

  const sizes = {};
  for (const file of files.sort()) {
    const { width, height } = await sharp(file).metadata();
    if (!width || !height) throw new Error(`Could not read the size of ${file}`);
    const key = path.relative(assetsDir, file).split(path.sep).join("/");
    sizes[key] = { width, height };
  }

  const body = Object.entries(sizes)
    .map(
      ([key, size]) =>
        `  ${JSON.stringify(key)}: { width: ${size.width}, height: ${size.height} },`,
    )
    .join("\n");

  await writeFile(
    manifestFile,
    `// Generated by scripts/optimize-images.mjs. Do not edit by hand.\n` +
      `export const imageSizes: Record<string, { width: number; height: number }> = {\n${body}\n};\n`,
  );
  console.log(`Wrote ${files.length} image sizes to ${path.relative(root, manifestFile)}`);
}

await optimizeScreenshots();
await writeSizeManifest();
